#Sled data type
dataFormat = '<iIfffffffffffffffffffffffffffiiiiffffffffffffffffffffiiiii'

#Dash data types
dataFormat = '<iIfffffffffffffffffffffffffffiiiiffffffffffffffffffffiiiiifffffffffffffffffHBBBBBBbbbffffi'

#Sled Variable names
ForzaTelemetryVariables = ['isRaceOn','TimestampMS','EngineMaxRPM','EngineIdleRPM','CurrentEngineRPM','AccelerationX','AccelerationY','AccelerationZ','VelocityX','VelocityY','VelocityZ','AngularVelocityX','AngularVelocityY','AngularVelocityZ','Yaw','Pitch','Roll','NormalizedSuspensionTravelFrontLeft','NormalizedSuspensionTravelFrontRight','NormalizedSuspensionTravelRearLeft','NormalizedSuspensionTravelRearRight','TireSlipRatioFrontLeft','TireSlipRatioFrontRight','TireSlipRatioRearLeft','TireSlipRatioRearRight','WheelRotationSpeedFrontLeft','WheelRotationSpeedFrontRight','WheelRotationSpeedRearLeft','WheelRotationSpeedRearRight','WheelOnRumbleStripFrontLeft','WheelOnRumbleStripFrontRight','WheelOnRumbleStripRearLeft','WheelOnRumbleStripRearRight','WheelInPuddleDepthFrontLeft','WheelInPuddleDepthFrontRight','WheelInPuddleDepthRearLeft','WheelInPuddleDepthRearRight','SurfaceRumbleFrontLeft','SurfaceRumbleFrontRight','SurfaceRumbleRearLeft','SurfaceRumbleRearRight','TireSlipAngleFrontLeft','TireSlipAngleFrontRight','TireSlipAngleRearLeft','TireSlipAngleRearRight','TireCombinedSlipFrontLeft','TireCombinedSlipFrontRight','TireCombinedSlipRearLeft','TireCombinedSlpRearRight','SuspensionTravelMetersFrontLeft','SuspensionTravelMetersFrontRight','SuspensionTravelMetersRearLeft','SuspensionTravelMetersRearRight','CarMake/Model','CarClass','CarPerformanceIndex','DrivetrainType','NumberOfCylinders']

#Dash Variable names
ForzaTelemetryVariables = ['isRaceOn','TimestampMS','EngineMaxRPM','EngineIdleRPM','CurrentEngineRPM','AccelerationX','AccelerationY','AccelerationZ','VelocityX','VelocityY','VelocityZ','AngularVelocityX','AngularVelocityY','AngularVelocityZ','Yaw','Pitch','Roll','NormalizedSuspensionTravelFrontLeft','NormalizedSuspensionTravelFrontRight','NormalizedSuspensionTravelRearLeft','NormalizedSuspensionTravelRearRight','TireSlipRatioFrontLeft','TireSlipRatioFrontRight','TireSlipRatioRearLeft','TireSlipRatioRearRight','WheelRotationSpeedFrontLeft','WheelRotationSpeedFrontRight','WheelRotationSpeedRearLeft','WheelRotationSpeedRearRight','WheelOnRumbleStripFrontLeft','WheelOnRumbleStripFrontRight','WheelOnRumbleStripRearLeft','WheelOnRumbleStripRearRight','WheelInPuddleDepthFrontLeft','WheelInPuddleDepthFrontRight','WheelInPuddleDepthRearLeft','WheelInPuddleDepthRearRight','SurfaceRumbleFrontLeft','SurfaceRumbleFrontRight','SurfaceRumbleRearLeft','SurfaceRumbleRearRight','TireSlipAngleFrontLeft','TireSlipAngleFrontRight','TireSlipAngleRearLeft','TireSlipAngleRearRight','TireCombinedSlipFrontLeft','TireCombinedSlipFrontRight','TireCombinedSlipRearLeft','TireCombinedSlpRearRight','SuspensionTravelMetersFrontLeft','SuspensionTravelMetersFrontRight','SuspensionTravelMetersRearLeft','SuspensionTravelMetersRearRight','CarMake/Model','CarClass','CarPerformanceIndex','DrivetrainType','NumberOfCylinders','PositionX','PositionY','PositionZ','Speed','Power','Torque','TireTempFrontLeft','TireTempFrontRight','TireTempRearLeft','TireTempRearRight','Boost','Fuel','DistanceTraveled','BestLap','LastLap','CurrentLap','CurrentRaceTime','LapNumber','RacePosition','Accel','Brake','Clutch','Steer','NormalisedDrivingLine','NormalisedAiBrakeDifference','TireWearFrontLeft','TireWearFrontRight','TireWearRearLeft','TireWearRearRight','TrackId']
